import type { Camera } from "@/pages/Index";

/** Sanitize a camera name into a valid stream key (lowercase, underscores) */
export function toStreamName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/** Resolve the best source URL for a camera (for use in config generation) */
export function resolveSourceUrl(cam: Camera): string | null {
  if (cam.sourceUrl && cam.sourceUrl.trim()) return cam.sourceUrl.trim();
  // For WebRTC streams, streamUrl is a stream *name*, not a source URL — we can't generate a source
  if (cam.protocol === "webrtc-go2rtc" || cam.protocol === "webrtc-mediamtx") return null;
  // For HLS/MJPEG/iframe the streamUrl IS the playback URL, not a source — still no RTSP source
  return null;
}

export interface GeneratedConfig {
  filename: string;
  content: string;
  cameras: { name: string; streamName: string; sourceUrl: string | null }[];
}

// ---------------------------------------------------------------------------
// go2rtc
// ---------------------------------------------------------------------------
export function generateGo2rtcConfig(cameras: Camera[], token?: string): GeneratedConfig {
  const entries = cameras
    .filter((c) => c.enabled)
    .map((cam) => {
      const streamName = toStreamName(cam.name);
      const source = resolveSourceUrl(cam);

      // If no sourceUrl but protocol is webrtc-go2rtc, use the streamUrl as an alias source hint
      const effectiveSource =
        source ??
        (cam.protocol === "webrtc-go2rtc" ? `# Set source for: ${cam.streamUrl}` : `# No source URL configured`);

      return { name: cam.name, streamName, sourceUrl: source, effectiveSource };
    });

  const lines: string[] = [
    "# Auto-generated by CamViewport",
    "# https://github.com/AlexxIT/go2rtc",
    "",
    "log:",
    "  level: info",
    "",
    "api:",
    "  listen: :1984",
    token ? `  # token: ${token}` : "  # token: your-secret-token",
    "",
    "streams:",
  ];

  for (const { name, streamName, sourceUrl, effectiveSource } of entries) {
    lines.push(`  # ${name}`);
    if (sourceUrl) {
      const withToken = token ? `${effectiveSource}?token=${token}` : effectiveSource;
      lines.push(`  ${streamName}:`);
      lines.push(`    - ${withToken}`);
    } else {
      lines.push(`  ${streamName}:`);
      lines.push(`    - ${effectiveSource}`);
    }
    lines.push("");
  }

  lines.push("webrtc:");
  lines.push("  ice_servers:");
  lines.push("    - urls: [stun:stun.l.google.com:19302]");

  return {
    filename: "go2rtc.yaml",
    content: lines.join("\n"),
    cameras: entries.map(({ name, streamName, sourceUrl }) => ({ name, streamName, sourceUrl })),
  };
}

// ---------------------------------------------------------------------------
// mediamtx
// ---------------------------------------------------------------------------
export function generateMediamtxConfig(cameras: Camera[], token?: string): GeneratedConfig {
  const entries = cameras
    .filter((c) => c.enabled)
    .map((cam) => {
      const streamName = toStreamName(cam.name);
      const source = resolveSourceUrl(cam);
      return { name: cam.name, streamName, sourceUrl: source };
    });

  const lines: string[] = [
    "# Auto-generated by CamViewport",
    "# https://github.com/bluenviron/mediamtx",
    "",
    "# API / metrics",
    "api: yes",
    "apiAddress: :9997",
    "",
    "# Protocols",
    "rtsp: yes",
    "rtspAddress: :8554",
    "rtsps: no",
    "",
    "rtmp: yes",
    "rtmpAddress: :1935",
    "",
    "hls: yes",
    "hlsAddress: :8888",
    "hlsAlwaysRemux: yes",
    "",
    "webrtc: yes",
    "webrtcAddress: :8889",
    "",
    token ? `# Authentication\n# authMethod: jwt\n\n` : "",
    "paths:",
  ];

  if (entries.length === 0) {
    lines.push("  # No cameras configured — add cameras in CamViewport first");
  }

  for (const { name, streamName, sourceUrl } of entries) {
    lines.push(`  # ${name}`);
    lines.push(`  ${streamName}:`);
    if (sourceUrl) {
      const withToken = token
        ? `${sourceUrl}${sourceUrl.includes("?") ? "&" : "?"}token=${token}`
        : sourceUrl;
      lines.push(`    source: ${withToken}`);
      lines.push(`    sourceOnDemand: yes`);
    } else {
      lines.push(`    source: publisher`);
      lines.push(`    # Configure your camera to publish to: rtsp://YOUR_HOST:8554/${streamName}`);
    }
    lines.push("");
  }

  // trim trailing blank line from token block
  const cleaned = lines.filter((l, i) => !(l === "" && i > 0 && lines[i - 1] === ""));

  return {
    filename: "mediamtx.yml",
    content: cleaned.join("\n"),
    cameras: entries.map(({ name, streamName, sourceUrl }) => ({ name, streamName, sourceUrl })),
  };
}
