[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=Xvfb %(ENV_DISPLAY)s -screen 0 %(ENV_XVFB_RESOLUTION)s -ac +extension GLX +render -noreset
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:x11vnc]
command=x11vnc -display %(ENV_DISPLAY)s -nopw -forever -shared -rfbport 5900 -passwd %(ENV_VNC_PASSWORD)s -loop -noxrecord -noxfixes -noxdamage
autorestart=true
priority=2
depends_on=xvfb
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:camviewport]
command=/usr/local/bin/camviewport -config /etc/camviewport/camviewport.ini
autorestart=true
priority=10
depends_on=xvfb
environment=DISPLAY="%(ENV_DISPLAY)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
